name: Auto Validate, Build, Release & Test

on:
  workflow_dispatch:
    ~
  push:
    branches: [master]
    paths:
      - "pakku.json"
      - "pakku-lock.json"
      - ".pakku/**"
  pull_request:
    branches: [master]
    paths:
      - "pakku.json"
      - "pakku-lock.json"
      - ".pakku/**"

permissions:
  contents: write
  pull-requests: write

jobs:
  json-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: json-validate
        id: json-validate
        uses: GrantBirki/json-yaml-validate@v3.3.2 # replace with the latest version
        with:
          comment: "true"
          base_dir: ".pakku"
          exclude_file: "exclude.txt"

  create-tag-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check if tag exists
        id: check_tag
        run: |
          if git rev-parse -q --verify "refs/tags/build" >/dev/null; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Create tag if missing
        if: steps.check_tag.outputs.exists == 'false'
        run: |
          git tag build
          git push origin build

      - name: Check if release exists
        id: check_release
        run: |
          release=$(gh release view build --json tagName -q .tagName || echo "none")
          if [ "$release" = "build" ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release if missing
        if: steps.check_release.outputs.exists == 'false'
        run: |
          gh release create build --title "Build Release" --notes "Automated release for build tag"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-release-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build Client
        run: |
          wget https://github.com/juraj-hrivnak/Pakku/releases/download/v1.3.2/pakku.jar >/dev/null 2>&1
          chmod 755 pakku.jar
          java -jar pakku.jar export

          mv ./build/curseforge/*.zip ./TskimiCupolaCraft-build.zip

      - name: Delete existing release assets
        uses: mknejp/delete-release-assets@v1
        with:
          fail-if-no-assets: false
          tag: build
          assets: |
            TskimiCupolaCraft-build.zip
            Server-TskimiCupolaCraft-build.zip
            Full-Server-TskimiCupolaCraft-build.zip
          token: ${{ secrets.GITHUB_TOKEN }} # Required for authentication

      - name: Upload client file to release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "build"
          files: |
            TskimiCupolaCraft-build.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build server
        run: |
          cp installer/install-server.sh ./install-server.sh 
          chmod +x install-server.sh
          ./install-server.sh
          zip -r "./Full-Server-TskimiCupolaCraft-build.zip" ./server/*

      - name: Package server files
        run: |
          cp pakku.json installer/
          cp pakku-lock.json installer/
          cp pakku.jar installer/
          cp -r MCDR/ installer/
          cp -r .pakku/ installer/
          wget https://maven.neoforged.net/releases/net/neoforged/neoforge/21.1.219/neoforge-21.1.219-installer.jar
          cp neoforge-21.1.219-installer.jar installer/
          rm -rf installer/.pakku/client-overrides/*
          
          shopt -s dotglob
          zip -r "./Server-TskimiCupolaCraft-build.zip" ./installer
          shopt -u dotglob

      - name: Upload server file to release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "build"
          files: |
            Server-TskimiCupolaCraft-build.zip 
            Full-Server-TskimiCupolaCraft-build.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Minecraft server and validate startup
        run: |
          cd server 
          chmod +x run.sh

          ./run.sh > server.log 2>&1 &
          SERVER_PID=$!

          echo "Test Server started with PID $SERVER_PID"

          for i in {1..30}; do
            if grep -q 'Done ([0-9.]\+s)! For help, type "help"' server.log; then
              echo "Server started successfully, running for additional 5 minutes to check stability."
              sleep 300
              if ! kill -0 $SERVER_PID 2>/dev/null; then
                echo "Server process crashed"
                break
              fi
              echo "Server started successfully"
              echo "Show log:"
              cat logs/latest.log
              exit 0
            fi
            if ! kill -0 $SERVER_PID 2>/dev/null; then
              echo "Server process crashed"
              break
            fi
            sleep 10
          done

          echo "Server did not start successfully within timeout or crashed"
          echo "Show log:"
          cat logs/kubejs/startup.log
          cat logs/latest.log

          if ls crash-reports/*.txt 1> /dev/null 2>&1; then
            echo "Crash reports found:"
            cat crash-reports/*.txt
          else
            echo "No crash reports found."
            cat logs/latest.log
          fi
          exit 1